//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGuate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasTelepeajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentasTelepeajes()
        {
            this.Tags = new HashSet<Tags>();
        }
    
        public long Id { get; set; }
        public string NumCuenta { get; set; }
        public string SaldoCuenta { get; set; }
        public string TypeCuenta { get; set; }
        public bool StatusCuenta { get; set; }
        public bool StatusResidenteCuenta { get; set; }
        public System.DateTime DateTCuenta { get; set; }
        public long ClienteId { get; set; }
        public string IdCajero { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
