//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGuate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoListas
    {
        public long Id { get; set; }
        public string Extension { get; set; }
        public string Tamaño { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Tipo { get; set; }
    }
}
