//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGuate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNegra
    {
        public long Id { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> SaldoAnterior { get; set; }
        public System.DateTime Date { get; set; }
        public string IdCajero { get; set; }
        public string Clase { get; set; }
        public string NumCliente { get; set; }
        public string NumCuenta { get; set; }
    }
}
