//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGuate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesCajeroes
    {
        public long Id { get; set; }
        public string Concepto { get; set; }
        public string TipoPago { get; set; }
        public Nullable<double> Monto { get; set; }
        public System.DateTime DateTOperacion { get; set; }
        public long CorteId { get; set; }
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> CobroTag { get; set; }
        public string NoReferencia { get; set; }
        public bool StatusCancelacion { get; set; }
    
        public virtual CortesCajeroes CortesCajeroes { get; set; }
    }
}
