//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGuate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametrizables
    {
        public int id { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public int extension { get; set; }
        public string destinoresidente { get; set; }
        public short cruzes { get; set; }
        public short minutos { get; set; }
    }
}
